server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/erictiong/spring-cloudconfig-wa-tolls.git
          search-paths:
            - 'station*'
          repos:
            perf:
              pattern:
              - '*/perf'
              uri: https://github.com/erictiong/spring-cloudconfig-wa-tolls-perf.git
              search-paths:
                - 'station*'
        encrypt:
          enabled: false
      enabled: true
  security:
    user:
      name: pluralsight
      password: pluralsight
security:
  basic:
    enabled: true
  enable-csrf: false
